[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
pm = dynamic
pm.max_children = 7
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500
request_terminate_timeout = 60s
slowlog = /var/log/php/www-slow.log
request_slowlog_timeout = 10s
request_slowlog_trace_depth = 20
rlimit_files = 1024
rlimit_core = 0
chdir = /srv/alina
catch_workers_output = yes
decorate_workers_output = no
clear_env = no
security.limit_extensions = .php
php_admin_value[error_log] = /var/log/php/php-fpm-error.log