server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name zero.home zero.zadobro.crazedns.ru azo.zadobro.crazedns.ru az.zero _;

    root /var/www/zero.home;
    absolute_redirect off;

    include conf.d/location.certbot;
    include conf.d/location.alina.php82;
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name zero.home zero.zadobro.crazedns.ru azo.zadobro.crazedns.ru az.zero _;

    root /var/www/zero.home;
    absolute_redirect off;

    proxy_read_timeout 300s;
    proxy_connect_timeout 75s;
    proxy_send_timeout 300s;

    ssl_certificate /srv/sewa/cert005gemini/070.byrobot.fullchain.pem;
    ssl_certificate_key /srv/sewa/cert005gemini/020.byrobot.privkey.pem;

    access_log /var/log/nginx/zero.home.access.log;
    access_log /var/log/nginx/alina.timing.log alina_timing;
    error_log /var/log/nginx/zero.home.error.log;

    include conf.d/location.certbot;
    include conf.d/location.alina.php82;
}
