server {
    server_name zero.home;
    listen 80;
    listen [::]:80;
    charset UTF-8;
    ssi on;
    include conf.d/location.certbot;

    location / {
        return 301 https://$host:443$request_uri;
    }
}

server {
    server_name zero.home;
    root /var/www/zero.home;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    proxy_read_timeout 300s;   # время ожидания ответа от бэкенда (PHP-FPM)
    proxy_connect_timeout 75s; # время на установку соединения с бэкендом
    proxy_send_timeout 300s;   # время на отправку запроса к бэкенду

    ssl_certificate /srv/sewa/cert003/cert/040.byrobot.fullchain.pem;
    ssl_certificate_key /srv/sewa/cert003/cert/030.byrobot.privkey.pem;

    include conf.d/location.certbot;
    include conf.d/location.alina;
}
