server {
    listen 443 ssl;
    server_name chat.saysimsim.ru;
    ssl_certificate /etc/letsencrypt/live/chat.saysimsim.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.saysimsim.ru/privkey.pem; # managed by Certbot


    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://saysimsim.ru:8080;
    }

    ##################################################
    #region PHP
    # pass PHP scripts to FastCGI server
    # https://stackoverflow.com/questions/15423500/nginx-showing-blank-php-pages/31905948#31905948
    location ~ \.php$ {
        # Check if file exists, otherwise return 404
        try_files $uri =404;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;

        # Use fastcgi.conf which usually includes SCRIPT_FILENAME
        include /etc/nginx/fastcgi.conf;

        # Ensure SCRIPT_FILENAME is set correctly if fastcgi.conf is missing it
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_intercept_errors on;
    }
    # I REMOVED:
    # proc
    # boot
    location ~ /(\.|\.well-known|bin|dev|etc|lib|run|sbin|sys|usr|var) {
        deny all;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location ~* \.(png|jpg|jpeg|gif|ico|svg|webp)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 1M;
        access_log off;
        add_header Cache-Control "public, immutable, max-age=2592000, no-transform" always;
        add_header Vary "Accept";
        gzip_static on;
        try_files $uri /noimage.png;
    }

    location ~* \.(js|css|html|woff2|ttf|eot|otf|map)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 1M;
        access_log off;
        add_header Cache-Control "public, immutable, max-age=2592000" always;
        gzip_static on;
        try_files $uri @notfound;
    }

    location ~* \.(mp3|mp4|wav|flac|avi)$ {
        add_header Accept-Ranges bytes;
        add_header Content-Disposition "inline";
        add_header X-Content-Type-Options nosniff always;

        aio threads;
        sendfile on;
        sendfile_max_chunk 512k;
        directio 1m;

        expires 1y;
        add_header Cache-Control "public, immutable, max-age=31536000";

        gzip off;

        limit_rate 1m;
        limit_rate_after 512k;
    }

    location @notfound {
        return 404;
        error_page 404 /notext.txt;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}