server {
    server_name zero.home;
    listen 80;
    listen [::]:80;
    charset UTF-8;
    ssi on;
    include conf.d/location.certbot;
    return 301 https://$host$request_uri;
}

server {
    server_name zero.home;
    root /var/www/zero.home;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    include conf.d/location.alina;
}
