server {
    client_max_body_size 100m;
    client_body_buffer_size 128k;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    
    listen 80;
    server_name zero.home;
    return 307 https://$server_name$request_uri;
}

server {
    client_max_body_size 100m;
    client_body_buffer_size 128k;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    listen 443 ssl;
    listen [::]:443 ssl;
    server_name zero.home;

    root /var/www/zero.home;
    error_log /var/log/nginx/zero.home.error.log;
    access_log /var/log/nginx/zero.home.access.log;

    # SSL/TLS
    ssl_certificate /srv/sewa/cert002/borg.home.crt;
    ssl_certificate_key /srv/sewa/cert002/borg.home.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:...;
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    # Static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|html|woff2|ttf|svg|eot|otf|map)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 1M;
        access_log off;
        add_header Cache-Control "public, immutable, max-age=2592000";
        try_files $uri /noimage.png;
        gzip_static on;
    }

    # PHP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi.conf;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_intercept_errors on;
    }

    # Fallback
    location / {
        try_files $uri $uri/ /index.php?alinapath=$uri&$args;
    }
}
