services:
  php82:
    build:
      context: ./docker/php82
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    env_file: _GITOUT/env/.env
    container_name: alina_php82
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
      - "9000"
    ports:
      - "8080:8080"
    volumes:
      # php.ini
      - ./server/usr82/local/etc/php/conf.d/alina.php.ini:/usr/local/etc/php/conf.d/alina.php.ini:ro
      - ./server/usr82/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./server/etc/supervisor/conf.d/chat.conf:/etc/supervisor/conf.d/chat.conf:ro
      - ./server/var/log/php/:/var/log/php/:rw
      # /var/www
      - ./server/var/www/:/var/www/:rw
      # ALINA framework
      - ./server/srv/:/srv/:rw
    working_dir: /srv/alina
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: true
    tmpfs:
      - /tmp
