services:

  php:
    build:
      context: ./docker/php84
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    env_file: _GITOUT/env/.env
    container_name: alina_php84
    links:
      - mysql
    expose:
      - "9000"
      - "9001"
    volumes:
      # php.ini
      - ./server/usr/local/etc/php/conf.d/alina.php.ini:/usr/local/etc/php/conf.d/alina.php.ini:ro
      - ./server/var/log/php/:/var/log/php/:rw
      # /var/www
      - ./server/var/www/:/var/www/:rw
      # ALINA framework
      - ./server/srv/:/srv/:ro
    working_dir: /srv/alina
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: false
    tmpfs:
      - /tmp
    depends_on:
      mysql:
        condition: service_healthy
