services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        mac_address: "aa:bb:cc:dd:ee:01"
        environment:
            TZ: "Europe/Moscow"
            WEBPASSWORD: "admin"
            FTLCONF_misc_etc_dnsmasq_d: "true"
            FTLCONF_dns_listeningMode: "all"
        volumes:
            - ./server_adt/etc/pihole/99-custom.conf:/etc/dnsmasq.d/99-custom.conf:ro
        restart: unless-stopped
        networks:
            local_network:
                ipv4_address: 192.168.1.200
        cap_add:
            - NET_ADMIN
            - NET_RAW

networks:
    local_network:
        driver: macvlan
        driver_opts:
            parent: enp4s0
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.254
