services:

  signaling:
    container_name: alina_signaling
    image: node:20-alpine
    restart: unless-stopped
    working_dir: /app
    environment:
      PORT: 3000
      NODE_ENV: production
    volumes:
      - type: bind
        source: ./server_signal
        target: /app
    command: sh -c "npm install && node signaling.prod.js"
    expose:
      - "3000"
