services:
  nginx:
    ports:
      - "50080:80"
      - "50443:443"

  mysql:
    ports:
      - "53306:3306"

  # region PHP74
  php:
    build:
      context: ./docker/php
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    env_file: _GITOUT/env/.env
    container_name: alina_php
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
      - "9000"
    volumes:
      # php.ini
      - ./server/usr/local/etc/php/conf.d/alina.php.ini:/usr/local/etc/php/conf.d/alina.php.ini:ro
      - ./server/var/log/php/:/var/log/php/:rw
      # /var/www
      - ./server/var/www/:/var/www/:rw
      # ALINA framework
      - ./server/srv/:/srv/:rw
    working_dir: /srv/alina
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: false
    tmpfs:
      - /tmp
  # endregion PHP74
  php-cs-fixer:
    image: ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.2
    container_name: alina_php_cs_fixer
    volumes:
      - ./server/var/www/:/apps/server/var/www/:rw
      - ./server/srv/:/apps/server/srv/:rw
      - ./.php-cs-fixer.dist.php:/apps/.php-cs-fixer.dist.php:ro
    working_dir: /apps
    user: "${UID:-33}:${GID:-33}"
    read_only: true
    tmpfs:
      - /tmp
