services:

  signaling:
    container_name: alina_signaling
    image: node:20-alpine
    restart: unless-stopped
    working_dir: /app
    environment:
      PORT: 3000
      NODE_ENV: production
    volumes:
      - type: bind
        source: ../ALINA_V/020.d/
        target: /app
    command: sh -c "npm install && npm run start"
    expose:
      - "3000"
