services:

  php:
    build:
      context: ./docker/php
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    env_file: _GITOUT/env/.env
    container_name: alina_php
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
      - "9000"
    volumes:
      # php.ini
      - ./server/usr/local/etc/php/conf.d/alina.php.ini:/usr/local/etc/php/conf.d/alina.php.ini:ro
      - ./server/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./server/var/log/php/:/var/log/php/:rw
      # /var/www
      - ./server/var/www/:/var/www/:rw
      # ALINA framework
      - ./server/srv/:/srv/:rw
    working_dir: /srv/alina
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: false
    tmpfs:
      - /tmp
