;;; B-CUSTOM
date.timezone = Europe/Moscow
memory_limit = 512M
upload_max_filesize = 5000M
post_max_size = 5120M
max_file_uploads = 100
upload_tmp_dir = /var/tmp/php-upload
max_execution_time = 14400
max_input_time = 14400
; Errors
display_errors = Off
log_errors = On
error_reporting = E_ALL
error_log = /var/log/php/php82-ini-error.log
