date.timezone = Europe/Moscow
memory_limit = 256M
upload_max_filesize = 11111M
post_max_size = 11111M
upload_tmp_dir = /tmp
max_execution_time = 333
max_input_time = 333
; Errors
display_errors = Off
log_errors = On
error_reporting = E_ALL
error_log = /var/log/php/php82-ini-error.log

