date.timezone = Europe/Moscow
memory_limit = 128M
upload_max_filesize = 1111M
post_max_size = 1111M
upload_tmp_dir = /tmp
max_execution_time = 33
max_input_time = 33
; Errors
display_errors = Off
log_errors = On
error_reporting = E_ALL
error_log = /var/log/php/php82-ini-error.log

